/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.dialog;

import javax.swing.JButton;

import org.jivesoftware.smack.AccountManager;
import org.jivesoftware.smack.XMPPConnection;
import org.jivesoftware.smack.packet.Presence;

import com.app.beans.DriverBean;
import com.app.database.DatabaseManager;
import com.app.database.DbConnectionManager;
import com.app.frame.ApplicationFrame;
import com.app.utils.Utils;
import com.app.xmpp.controller.XmppManager;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.UIManager;
import java.awt.Font;

public class AddDriverInformations extends javax.swing.JDialog {

	private ApplicationFrame frame;

	/**
	 * Creates new form DriverListJDialog
	 */
	public AddDriverInformations(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		frame = (ApplicationFrame) parent;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		driverId_txtfield = new javax.swing.JTextField();
		password_txtfield = new javax.swing.JPasswordField();
		phone_txtfield = new javax.swing.JTextField();
		email_txtfield = new javax.swing.JTextField();
		tractor_txtfield = new javax.swing.JTextField();
		add_button = new JButton("Add");
		jLabel7 = new javax.swing.JLabel();
		trailor_txtfield = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		username_txtfield = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		firstname_txtfield = new javax.swing.JTextField();
		lastname_txtfield = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));
		setResizable(false);

		jPanel1.setBackground(Color.DARK_GRAY);

		jPanel2.setBackground(new Color(135, 206, 235));

		jLabel6.setFont(new Font("Cambria Math", Font.PLAIN, 24)); // NOI18N
		jLabel6.setText("Add New Driver");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2Layout.setHorizontalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addGap(134)
					.addComponent(jLabel6)
					.addContainerGap(144, Short.MAX_VALUE))
		);
		jPanel2Layout.setVerticalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addGap(21)
					.addComponent(jLabel6)
					.addContainerGap(25, Short.MAX_VALUE))
		);
		jPanel2.setLayout(jPanel2Layout);

		jPanel3.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel1.setText("Driver Id");

		jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel2.setText("Password");

		jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel3.setText("Phone No");

		jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel4.setText("Email Id");

		jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel5.setText("Tractor");

		driverId_txtfield.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

		password_txtfield.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

		phone_txtfield.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

		email_txtfield.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

		tractor_txtfield.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

		add_button.setText("Save");
		add_button.setFocusable(false);
		add_button.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				add_buttonMouseClicked(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel7.setText("Trailor");

		trailor_txtfield.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

		jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel8.setText("UserName");

		username_txtfield.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

		jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel9.setText("FirstName");

		jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		jLabel10.setText("LastName");

		firstname_txtfield.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
		firstname_txtfield
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						firstname_txtfieldActionPerformed(evt);
					}
				});

		lastname_txtfield.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3Layout.setHorizontalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addGap(48)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel8)
						.addComponent(jLabel1)
						.addComponent(jLabel2)
						.addComponent(jLabel9)
						.addComponent(jLabel10)
						.addComponent(jLabel3)
						.addComponent(jLabel4)
						.addComponent(jLabel7)
						.addComponent(jLabel5))
					.addPreferredGap(ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING, false)
						.addComponent(trailor_txtfield)
						.addComponent(tractor_txtfield, Alignment.LEADING)
						.addComponent(driverId_txtfield, Alignment.LEADING)
						.addComponent(phone_txtfield, Alignment.LEADING)
						.addComponent(email_txtfield, Alignment.LEADING)
						.addComponent(username_txtfield, Alignment.LEADING)
						.addComponent(password_txtfield, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
						.addComponent(firstname_txtfield)
						.addComponent(lastname_txtfield, Alignment.LEADING))
					.addGap(52))
				.addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
					.addContainerGap(190, Short.MAX_VALUE)
					.addComponent(add_button, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
					.addGap(183))
		);
		jPanel3Layout.setVerticalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(driverId_txtfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(username_txtfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel8))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(password_txtfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(firstname_txtfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel9))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(lastname_txtfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel10))
							.addPreferredGap(ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(phone_txtfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(email_txtfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(tractor_txtfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5))
							.addGap(70))
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addGap(301)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(trailor_txtfield, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel7))
							.addGap(34)))
					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(add_button)
					.addGap(36))
		);
		jPanel3.setLayout(jPanel3Layout);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanel3,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void add_buttonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_add_buttonMouseClicked
		// TODO add your handling code here:
		addDriver();
	}// GEN-LAST:event_add_buttonMouseClicked

	private void firstname_txtfieldActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_firstname_txtfieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_firstname_txtfieldActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					AddDriverInformations.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					AddDriverInformations.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					AddDriverInformations.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					AddDriverInformations.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				AddDriverInformations dialog = new AddDriverInformations(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton add_button;
	private javax.swing.JTextField driverId_txtfield;
	private javax.swing.JTextField email_txtfield;
	private javax.swing.JTextField firstname_txtfield;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JTextField lastname_txtfield;
	private javax.swing.JPasswordField password_txtfield;
	private javax.swing.JTextField phone_txtfield;
	private javax.swing.JTextField tractor_txtfield;
	private javax.swing.JTextField trailor_txtfield;
	private javax.swing.JTextField username_txtfield;

	// End of variables declaration//GEN-END:variables

	/**
	 * Insert Driver Informations into Database
	 */
	private void addDriver() {

		try {
			String driverId = driverId_txtfield.getText();
			String username = username_txtfield.getText();
			String password = password_txtfield.getText();
			String firstname = firstname_txtfield.getText();
			String lastname = lastname_txtfield.getText();
			String tractor = tractor_txtfield.getText();
			String trailor = trailor_txtfield.getText();
			String phone = phone_txtfield.getText();
			String email = email_txtfield.getText();

			DriverBean bean = new DriverBean();
			bean.setDriverId(driverId);
			bean.setUsername(username);
			bean.setPassword(password);
			bean.setFirstname(firstname);
			bean.setLastname(lastname);
			bean.setTractor(tractor);
			bean.setTrailor(trailor);
			bean.setPhone(phone);
			bean.setEmail(email);

			if (XmppManager.getConnection() != null) {
				if (DatabaseManager.getInstance() != null) {
					if (DbConnectionManager.getConnection() != null) {
						XMPPConnection connection = XmppManager.getConnection();
						AccountManager accountManager = connection
								.getAccountManager();
						accountManager.createAccount(username, password);
						Presence subscribe = new Presence(
								Presence.Type.subscribe);
						subscribe.setTo(username + "@localhost");
						connection.sendPacket(subscribe);
						Presence subscribed = new Presence(
								Presence.Type.subscribed);
						subscribed.setTo("admin@localhost");
						connection.sendPacket(subscribed);
						//

						subscribe = new Presence(Presence.Type.subscribe);
						subscribe.setTo("admin@localhost");
						connection.sendPacket(subscribe);
						subscribed = new Presence(Presence.Type.subscribed);
						subscribed.setTo(username + "@localhost");
						connection.sendPacket(subscribed);
						//

						boolean flag = DatabaseManager.getInstance()
								.insertDriver(
										DbConnectionManager.getConnection(),
										bean);
						if (flag) {
							frame.updateDriverList();
							frame.updateChatUserList();
							AddDriverInformations.this.dispose();
						}
					}
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
			Utils.infoBox("User Already Exist", "Add Driver");
		}
	}
}
